const auth = [{ cookieAuth: [] }, { bearerAuth: [] }];
const json = (schema) => ({ required: true, content: { 'application/json': { schema } } });
const idParameter = { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } };
const oficioParameter = { name: 'oficioId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } };

module.exports = {
  openapi: '3.0.3',
  info: { title: 'ServiMap API', version: '1.1.0', description: 'API real de ServiMap. La aplicación web usa una cookie JWT HttpOnly; clientes externos también pueden enviar Bearer JWT.' },
  servers: [{ url: '/api' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }, cookieAuth: { type: 'apiKey', in: 'cookie', name: 'servimap_session' } },
    schemas: {
      Error: { type: 'object', properties: { error: { type: 'string' } } },
      Registro: { type: 'object', required: ['nombre', 'apellido', 'email', 'password', 'confirmacion', 'rol'], properties: { nombre: { type: 'string', maxLength: 80 }, apellido: { type: 'string', maxLength: 80 }, email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 8, format: 'password' }, confirmacion: { type: 'string', minLength: 8, format: 'password' }, rol: { type: 'string', enum: ['CLIENTE', 'PRESTADOR'] } } },
      Login: { type: 'object', required: ['email', 'password', 'rol'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' }, rol: { type: 'string', enum: ['CLIENTE', 'PRESTADOR', 'ADMINISTRADOR'] } } },
      OficioInput: { type: 'object', required: ['nombre', 'categoria'], properties: { nombre: { type: 'string', maxLength: 80 }, categoria: { type: 'string', maxLength: 80 }, isActivo: { type: 'boolean' } } },
      PerfilPrestador: { type: 'object', properties: { descripcionProfesional: { type: 'string', maxLength: 2000 }, fotoPerfil: { type: 'string', format: 'uri', maxLength: 500 }, zonaCobertura: { type: 'string', maxLength: 120 }, telefono: { type: 'string', maxLength: 40 }, latitud: { type: 'number', minimum: -90, maximum: 90 }, longitud: { type: 'number', minimum: -180, maximum: 180 }, isDisponible: { type: 'boolean' } } },
      ServicioInput: { type: 'object', required: ['modalidadPrecio'], properties: { modalidadPrecio: { type: 'string', enum: ['FIJO', 'RANGO'] }, precio: { type: 'number', exclusiveMinimum: 0, nullable: true }, precioMinimo: { type: 'number', exclusiveMinimum: 0, nullable: true }, precioMaximo: { type: 'number', exclusiveMinimum: 0, nullable: true }, isDisponible: { type: 'boolean' } } },
      UbicacionCliente: { type: 'object', required: ['latitudUbicacion', 'longitudUbicacion'], properties: { latitudUbicacion: { type: 'number', minimum: -90, maximum: 90 }, longitudUbicacion: { type: 'number', minimum: -180, maximum: 180 } } },
      SolicitudInput: { type: 'object', required: ['prestadorId', 'oficioId', 'descripcion'], properties: { prestadorId: { type: 'string', format: 'uuid' }, oficioId: { type: 'string', format: 'uuid' }, descripcion: { type: 'string', maxLength: 2000 } } },
      EstadoSolicitud: { type: 'object', required: ['estado'], properties: { estado: { type: 'string', enum: ['PROPUESTA_ENVIADA', 'ACEPTADA', 'RECHAZADA', 'CANCELADA', 'FINALIZADA'] } } },
      CalificacionInput: { type: 'object', required: ['solicitudId', 'puntaje', 'comentario'], properties: { solicitudId: { type: 'string', format: 'uuid' }, puntaje: { type: 'integer', minimum: 1, maximum: 5 }, comentario: { type: 'string', maxLength: 1000 } } },
      ModeracionInput: { type: 'object', required: ['isModerada'], properties: { isModerada: { type: 'boolean' }, motivo: { type: 'string', maxLength: 500 } } },
    },
  },
  paths: {
    '/health': { get: { tags: ['Sistema'], summary: 'Comprobar que Express responde', responses: { 200: { description: 'API disponible' } } } },
    '/auth/registro': { post: { tags: ['Autenticación'], summary: 'Registrar cliente o prestador y crear cookie HttpOnly', requestBody: json({ $ref: '#/components/schemas/Registro' }), responses: { 201: { description: 'Cuenta creada y sesión iniciada' }, 400: { description: 'Datos inválidos' }, 409: { description: 'Email duplicado' }, 429: { description: 'Límite de intentos excedido' } } } },
    '/auth/login': { post: { tags: ['Autenticación'], summary: 'Iniciar sesión mediante cookie JWT HttpOnly', requestBody: json({ $ref: '#/components/schemas/Login' }), responses: { 200: { description: 'Sesión iniciada' }, 401: { description: 'Credenciales incorrectas' }, 403: { description: 'Cuenta inactiva' }, 429: { description: 'Límite de intentos excedido' } } } },
    '/auth/logout': { post: { tags: ['Autenticación'], summary: 'Cerrar sesión y eliminar cookie', responses: { 204: { description: 'Sesión cerrada' } } } },
    '/auth/me': { get: { tags: ['Autenticación'], summary: 'Obtener usuario autenticado', security: auth, responses: { 200: { description: 'Usuario actual' }, 401: { description: 'Sesión inválida' } } } },
    '/oficios': { get: { tags: ['Oficios'], summary: 'Listar oficios activos', responses: { 200: { description: 'Listado' } } }, post: { tags: ['Oficios'], summary: 'Crear oficio', security: auth, requestBody: json({ $ref: '#/components/schemas/OficioInput' }), responses: { 201: { description: 'Oficio creado' }, 403: { description: 'Sólo administrador' }, 409: { description: 'Nombre duplicado' } } } },
    '/oficios/admin': { get: { tags: ['Oficios'], summary: 'Listar oficios activos e inactivos', security: auth, responses: { 200: { description: 'Listado administrativo' }, 403: { description: 'Sólo administrador' } } } },
    '/oficios/{id}': { get: { tags: ['Oficios'], summary: 'Consultar oficio activo', parameters: [idParameter], responses: { 200: { description: 'Oficio' }, 404: { description: 'No encontrado' } } }, put: { tags: ['Oficios'], summary: 'Editar nombre o categoría', security: auth, parameters: [idParameter], requestBody: json({ $ref: '#/components/schemas/OficioInput' }), responses: { 200: { description: 'Actualizado' }, 403: { description: 'Sólo administrador' } } } },
    '/oficios/{id}/estado': { patch: { tags: ['Oficios'], summary: 'Activar o desactivar oficio', security: auth, parameters: [idParameter], requestBody: json({ type: 'object', required: ['isActivo'], properties: { isActivo: { type: 'boolean' } } }), responses: { 200: { description: 'Estado actualizado' } } } },
    '/prestadores': { get: { tags: ['Prestadores'], summary: 'Buscar perfiles completos y disponibles', parameters: [{ name: 'oficioId', in: 'query', schema: { type: 'string' } }, { name: 'zona', in: 'query', schema: { type: 'string' } }, { name: 'texto', in: 'query', schema: { type: 'string' } }, { name: 'latitud', in: 'query', schema: { type: 'number' } }, { name: 'longitud', in: 'query', schema: { type: 'number' } }, { name: 'distancia', in: 'query', schema: { type: 'number', maximum: 500 } }], responses: { 200: { description: 'Perfiles con coordenadas públicas aproximadas' } } } },
    '/prestadores/me': { get: { tags: ['Prestadores'], summary: 'Consultar perfil propio con coordenadas privadas', security: auth, responses: { 200: { description: 'Perfil propio' }, 403: { description: 'Sólo prestador' } } }, put: { tags: ['Prestadores'], summary: 'Actualizar perfil propio', security: auth, requestBody: json({ $ref: '#/components/schemas/PerfilPrestador' }), responses: { 200: { description: 'Perfil actualizado' }, 400: { description: 'Datos inválidos' } } } },
    '/prestadores/me/oficios/{oficioId}': { put: { tags: ['Prestadores'], summary: 'Añadir o actualizar oficio ofrecido', security: auth, parameters: [oficioParameter], requestBody: json({ $ref: '#/components/schemas/ServicioInput' }), responses: { 200: { description: 'Servicio actualizado' } } }, delete: { tags: ['Prestadores'], summary: 'Quitar oficio propio', security: auth, parameters: [oficioParameter], responses: { 204: { description: 'Servicio eliminado' } } } },
    '/prestadores/{id}': { get: { tags: ['Prestadores'], summary: 'Consultar perfil público', parameters: [idParameter], responses: { 200: { description: 'Perfil con reseñas visibles y ubicación aproximada' }, 404: { description: 'Perfil incompleto o inexistente' } } } },
    '/clientes/me': { get: { tags: ['Clientes'], summary: 'Consultar ubicación privada propia', security: auth, responses: { 200: { description: 'Perfil del cliente' } } }, put: { tags: ['Clientes'], summary: 'Actualizar ubicación privada', security: auth, requestBody: json({ $ref: '#/components/schemas/UbicacionCliente' }), responses: { 200: { description: 'Ubicación guardada' } } } },
    '/solicitudes': { get: { tags: ['Solicitudes'], summary: 'Listar solicitudes visibles para el rol', security: auth, responses: { 200: { description: 'Listado' } } }, post: { tags: ['Solicitudes'], summary: 'Crear solicitud para un servicio ofrecido', security: auth, requestBody: json({ $ref: '#/components/schemas/SolicitudInput' }), responses: { 201: { description: 'Solicitud pendiente creada' }, 400: { description: 'Servicio no ofrecido' } } } },
    '/solicitudes/{id}': { get: { tags: ['Solicitudes'], summary: 'Consultar solicitud propia o administrativa', security: auth, parameters: [idParameter], responses: { 200: { description: 'Solicitud' }, 403: { description: 'Recurso ajeno' } } } },
    '/solicitudes/{id}/estado': { patch: { tags: ['Solicitudes'], summary: 'Cambiar estado con transición y propietario válidos', security: auth, parameters: [idParameter], requestBody: json({ $ref: '#/components/schemas/EstadoSolicitud' }), responses: { 200: { description: 'Estado actualizado' }, 403: { description: 'Recurso ajeno' }, 409: { description: 'Transición inválida o conflicto concurrente' } } } },
    '/calificaciones': { post: { tags: ['Calificaciones'], summary: 'Calificar trabajo propio finalizado', security: auth, requestBody: json({ $ref: '#/components/schemas/CalificacionInput' }), responses: { 201: { description: 'Calificación creada' }, 403: { description: 'Solicitud ajena' }, 409: { description: 'No finalizada o ya calificada' } } } },
    '/calificaciones/moderacion': { get: { tags: ['Calificaciones'], summary: 'Listar reseñas para moderación', security: auth, responses: { 200: { description: 'Listado' }, 403: { description: 'Sólo administrador' } } } },
    '/calificaciones/{id}/moderacion': { patch: { tags: ['Calificaciones'], summary: 'Ocultar o restaurar comentario conservando puntaje', security: auth, parameters: [idParameter], requestBody: json({ $ref: '#/components/schemas/ModeracionInput' }), responses: { 200: { description: 'Moderación actualizada' }, 403: { description: 'Sólo administrador' } } } },
  },
};
