import { useEffect, useState } from 'react';
import apiClient from '../services/apiClient';
import { readProfileImage } from '../utils/images';

export default function ClientProfile() {
  const [form, setForm] = useState(null); const [editing, setEditing] = useState(false);
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false);
  const load = () => apiClient.get('/clientes/me').then(({ data }) => setForm(data));
  useEffect(() => { const timer = window.setTimeout(() => load().catch(() => setError('No pudimos cargar tu perfil.')), 0); return () => window.clearTimeout(timer); }, []);
  const locate = () => navigator.geolocation?.getCurrentPosition(({ coords }) => setForm({ ...form, latitudUbicacion: coords.latitude.toFixed(5), longitudUbicacion: coords.longitude.toFixed(5) }), () => setError('No pudimos acceder a tu ubicación. Podés continuar sin usarla.'));
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { const { data } = await apiClient.put('/clientes/me', form); setForm(data); setEditing(false); setMessage('Perfil actualizado.'); } catch (requestError) { setError(requestError.response?.data?.error || 'No pudimos guardar tu perfil.'); } };
  const upload = async (event) => { try { setError(''); setUploading(true); const dataUrl = await readProfileImage(event.target.files?.[0]); if (!dataUrl) return; const { data } = await apiClient.post('/clientes/me/foto', { dataUrl }); setForm(data); setMessage('Foto actualizada.'); } catch (uploadError) { setError(uploadError.response?.data?.error || uploadError.message); } finally { setUploading(false); event.target.value = ''; } };
  if (!form) return <div className="screen-message">{error || 'Cargando tu perfil…'}</div>;
  const initials = `${form.nombre?.[0] || ''}${form.apellido?.[0] || ''}`.toUpperCase();
  return <section className="client-profile"><div className="page-heading"><span className="eyebrow">Mi cuenta</span><h1>Mi perfil</h1><p>Administrá tus datos y la ubicación privada utilizada para calcular distancias.</p></div>
    <article className="card client-profile-card"><div className="profile-photo-wrap">{form.fotoPerfil ? <img className="provider-profile-photo" src={form.fotoPerfil} alt={`Foto de ${form.nombre}`} /> : <div className="avatar provider-profile-photo provider-profile-initials">{initials}</div>}<label className="text-link upload-link">{uploading ? 'Subiendo…' : 'Cambiar foto'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading} /></label></div>
      {!editing ? <><div className="client-profile-copy"><h2>{form.nombre} {form.apellido}</h2><p>{form.email}</p><small>La ubicación exacta nunca se muestra a los prestadores.</small></div><button className="button secondary" onClick={() => setEditing(true)}>Editar perfil</button></> : <form className="form-grid client-profile-form" onSubmit={submit}><label>Nombre<input value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} required /></label><label>Apellido<input value={form.apellido} onChange={(e) => setForm({ ...form, apellido: e.target.value })} required /></label><label className="full">Correo<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label>Latitud privada<input type="number" step="any" value={form.latitudUbicacion ?? ''} onChange={(e) => setForm({ ...form, latitudUbicacion: e.target.value })} /></label><label>Longitud privada<input type="number" step="any" value={form.longitudUbicacion ?? ''} onChange={(e) => setForm({ ...form, longitudUbicacion: e.target.value })} /></label><button type="button" className="button subtle" onClick={locate}>Usar mi ubicación</button><div className="button-row"><button className="button primary">Guardar</button><button type="button" className="button subtle" onClick={() => { load(); setEditing(false); }}>Cancelar</button></div></form>}
    </article>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}
  </section>;
}
