import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import apiClient from '../services/apiClient';
import { useAuth } from '../context/auth-context';
import { formatTradePrice } from '../utils/prices';

export default function ProviderProfile() {
  const { id } = useParams(); const { usuario } = useAuth();
  const [provider, setProvider] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [request, setRequest] = useState({ oficioId: '', descripcion: '' });
  useEffect(() => { apiClient.get(`/prestadores/${id}`).then(({ data }) => { setProvider(data); setRequest((current) => ({ ...current, oficioId: data.oficios.find((item) => item.isDisponible)?.id || '' })); }).catch((requestError) => setError(requestError.response?.data?.error || 'No pudimos cargar el perfil')); }, [id]);
  const submit = async (event) => { event.preventDefault(); setError(''); try { await apiClient.post('/solicitudes', { ...request, prestadorId: id }); setMessage('Solicitud enviada. Podés seguirla desde Mis solicitudes.'); setRequest({ ...request, descripcion: '' }); } catch (requestError) { setError(requestError.response?.data?.error || 'No pudimos enviar la solicitud'); } };
  if (error && !provider) return <div className="screen-message"><p>{error}</p><Link to="/app/buscar">Volver a buscar</Link></div>;
  if (!provider) return <div className="screen-message">Cargando perfil…</div>;
  const profile = <main className="profile-layout"><section className="profile-main card"><Link className="text-link profile-back" to="/app/buscar">← Volver a resultados</Link><div className="profile-title">{provider.fotoPerfil ? <img className="avatar large provider-public-photo" src={provider.fotoPerfil} alt={`Foto de ${provider.nombre}`} /> : <div className="avatar large">{provider.nombre.split(/\s+/).slice(0, 2).map((part) => part[0]).join('')}</div>}<div><span className="eyebrow">Profesional en ServiMap</span><h1>{provider.nombre}</h1><p>{provider.zonaCobertura} · {provider.isDisponible ? 'Disponible' : 'No disponible'}{provider.promedioCalificaciones != null ? ` · ★ ${provider.promedioCalificaciones} (${provider.cantidadCalificaciones})` : ''}</p></div></div>
      <h2>Acerca de su trabajo</h2><p>{provider.descripcionProfesional}</p><div className="provider-public-stats"><span><strong>{provider.trabajosFinalizados ?? 0}</strong> trabajos finalizados</span><span><strong>{provider.cantidadCalificaciones ?? 0}</strong> reseñas</span></div><h2>Servicios y precios orientativos</h2><div className="service-list">{provider.oficios.map((item) => <div key={item.id}><strong>{item.nombre}</strong><span>{formatTradePrice(item)}</span></div>)}</div>
      <h2>Reseñas</h2>{provider.resenas.length ? provider.resenas.map((review) => <blockquote key={review.id}><strong>{'★'.repeat(review.puntaje)}</strong><p>{review.comentario}</p></blockquote>) : <p className="muted">Todavía no hay reseñas visibles.</p>}
    </section><aside className="card request-card"><h2>Solicitar servicio</h2>{usuario?.rol === 'CLIENTE' ? <form onSubmit={submit}><label>Oficio<select value={request.oficioId} onChange={(e) => setRequest({ ...request, oficioId: e.target.value })} required>{provider.oficios.filter((item) => item.isDisponible).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label><label>Contale qué necesitás<textarea rows="5" maxLength="2000" value={request.descripcion} onChange={(e) => setRequest({ ...request, descripcion: e.target.value })} required /></label><small className="character-count">{request.descripcion.length}/2000</small>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="button primary">Enviar solicitud</button></form> : <><p>Iniciá sesión como cliente para contactar a este profesional.</p><Link className="button primary" to="/login">Iniciar sesión</Link></>}</aside></main>;
  return usuario?.rol === 'CLIENTE' ? profile : <div className="public-page"><header className="public-header"><Link className="brand" to="/login">ServiMap</Link><Link className="text-link" to="/">Volver</Link></header>{profile}</div>;
}
